# Configuration file for Azure DevOps Pipeline

variables:
  TARGET_DIR: '.'
  VBA_DIR: 'vba-src'

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude: 
      - $(VBA_DIR)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- checkout: self
  submodules: true
  persistCredentials: true
  clean: true

- script: |
    echo Set Requestor as $(Build.RequestedFor) $(Build.RequestedForEmail)
    git config --global user.email $(Build.RequestedForEmail)
    git config --global user.name $(Build.RequestedFor)
    if ["$(System.PullRequest.SourceBranch)" = ""]; then
      echo Checkout for branch $(Build.SourceBranch)
      export branchname=$(echo $(Build.SourceBranch) | sed s@refs/heads/@@)
    else
      echo Checkout for PR source branch $(System.PullRequest.SourceBranch)
      export branchname=$(echo $(System.PullRequest.SourceBranch) | sed s@refs/heads/@@)      
    fi
    echo Checkout for branch-name $branchname
    git remote update
    git fetch origin $branchname
    git checkout $branchname
  displayName: 'Set the configuration for git commit/push.'

- script: |
    echo Install pipenv
    python -m pip install pip --upgrade
    pip install pipenv
    echo Install extract_vba_source
    git clone https://github.com/takeruko/extract_vba_source.git
  displayName: 'Install extract_vba_source.py.'

- script: |
    echo Specify the location of the Pipfile and run extract_vba_source.py
    export PIPENV_PIPFILE=$(pwd)/extract_vba_source/Pipfile
    pipenv install
    pipenv run python ./extract_vba_source/extract_vba_source.py \
                      --dest $(VBA_DIR) \
                      --src-encoding='cp932' \
                      --out-encoding='utf8' \
                      --recursive \
                      $(TARGET_DIR)
  displayName: 'Extract vba source files.'

- script: |
    git status
    git add $(VBA_DIR)
    git status
    git commit -m "Extracted vba source files. [skip ci]"
    git push origin $branchname
  displayName: 'Commit vba source files.'
  
